# Generated by Django 2.2 on 2019-04-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='review_deck',
        ),
        migrations.AddField(
            model_name='deck',
            name='ownership',
            field=models.BooleanField(default=False, verbose_name='Ownership'),
        ),
    ]
