# Generated by Django 2.2 on 2019-04-03 20:44

from django.db import migrations
from django.conf import settings
import os.path
import csv
from django.core.files import File
from django.template.defaultfilters import slugify

def import_initial_decks(apps, schema_editor):
    """
    Read a CSV file full of posts and insert them into the database.
    """
    Deck = apps.get_model('core', 'Deck')
    Profile = apps.get_model('core', 'Profile')
    Category = apps.get_model('core', 'Category')
    User = apps.get_model('auth', 'User')

    Deck.objects.all().delete()
    datapath = os.path.join(settings.BASE_DIR, 'core/database')
    datafile = os.path.join(datapath, 'deck_data.csv')

    with open(datafile) as file:
        reader = csv.DictReader(file) 
        for row in reader:
            #set Deck_site_name so that you can only add posts that haven't been added
            deck_title = row['title']

            if Deck.objects.filter(title=deck_title).count():
                return
            #if the title isn't there, make new deck
            user, _ = User.objects.get_or_create(username=row['created_by'])
            created_by, _ = Profile.objects.get_or_create(user=user)
            category, _ = Category.objects.get_or_create(deck_category=row['category'],slug=slugify(row['category']))

            deck = Deck(
                title=row['title'],
                created_by=created_by,
                category=category,
                ownership=row['ownership'],
                slug=row['slug']
                
            )

            deck.save()

            


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190403_1555'),
    ]

    operations = [
        migrations.RunPython(import_initial_decks),
    ]
