#Generated by Django 2.2 on 2019-04-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190403_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
