# Generated by Django 2.2 on 2019-04-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190403_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='answered_correctly',
            field=models.BooleanField(default=False, verbose_name='Answered correctly'),
        ),
    ]
