# Generated by Django 2.2 on 2019-04-05 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_card_answered_correctly'),
        ('core', '0005_auto_20190405_0941'),
    ]

    operations = [
    ]
