# Generated by Django 2.2 on 2019-04-05 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20190405_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='decks',
        ),
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.Deck'),
            preserve_default=False,
        ),
    ]
