# Generated by Django 2.2 on 2019-04-05 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190405_1510'),
        ('core', '0006_merge_20190405_1213'),
    ]

    operations = [
    ]
